#pragma once

// Curated auth-anchored brand-identity KB (doc-12 north star, TASK-232). The
// Tranco top-10k reputation set is the broad ham-rescue; this is the small, finite,
// hand-curated set of high-value impersonated brands with their CANONICAL sending
// domains (brand_kb_data.h, generated by gen_brand_kb.py). Two uses:
//   - is_canonical_domain: the sender IS the brand on a domain it owns -> exempt
//     from the impersonation signal (fixes mid-tier-brand FPs the top-10k misses:
//     BoursoBank@boursorama.fr, Navigo@iledefrance-mobilites.fr, Cushon@cushon.co.uk).
//   - cousin detection: a TLD-swap (paypal.co vs paypal.com, is_tld_swap_kb), a
//     typosquat (paypall, typosquat_target_kb, claim-gated by the caller) or an IDN
//     homoglyph (is_idn_lookalike_kb) of a DISTINCTIVE brand domain (TASK-214 AC#3).

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "brand_kb_data.h"
#include "brand_names.h"  // domain_stem + brand_tier (distinctive-brand gate)
#include "fnv1a.h"


namespace spam_engine::brand_kb {

// The full org-domain is a canonical brand domain (apple.com, boursorama.fr).
inline bool is_canonical_domain(const std::string& org_domain) {
  if (org_domain.empty()) { return false;
}
  const std::uint64_t h = fnv1a_lower(org_domain);
  return std::binary_search(kKbCanonicalHashes, kKbCanonicalHashes + kKbCanonicalHashesCount, h);
}

// Claimed-vs-authenticated lookup (TASK-232 AC#2, doc-12 north star). The pairs
// (brand-name hash, authenticated-domain hash) are emitted sorted by gen_brand_kb.py
// from the curated seed + the auto-resolved set (brand_authdomains.json, AC#1), keyed
// by the brand name a display claims ("apple", "orange", "visa"). Lexicographic order
// on (brand, domain) lets one binary search test exact membership and a lower_bound
// test whether the brand is known at all.
inline bool kb_auth_pair_less(const KbBrandAuthPair& a, const KbBrandAuthPair& b) {
  return a.brand < b.brand || (a.brand == b.brand && a.domain < b.domain);
}

// The KB knows brand X's authenticated sending domains (so a mismatch is meaningful).
inline bool brand_has_auth_set(const std::string& brand) {
  if (brand.empty()) { return false;
}
  const KbBrandAuthPair key{fnv1a_lower(brand), 0};
  const KbBrandAuthPair* end = kKbBrandAuthPairs + kKbBrandAuthPairsCount;
  const KbBrandAuthPair* it = std::lower_bound(kKbBrandAuthPairs, end, key, kb_auth_pair_less);
  return it != end && it->brand == key.brand;
}

// org_domain is one of brand X's authenticated sending domains (X claimed it, X sent it).
inline bool domain_in_brand_auth_set(const std::string& brand, const std::string& org_domain) {
  if (brand.empty() || org_domain.empty()) { return false;
}
  const KbBrandAuthPair key{fnv1a_lower(brand), fnv1a_lower(org_domain)};
  return std::binary_search(kKbBrandAuthPairs, kKbBrandAuthPairs + kKbBrandAuthPairsCount,
                            key, kb_auth_pair_less);
}

// org_domain appears in ANY brand's authenticated set (brand-agnostic membership,
// for the kb_brand_dmarc_pass rescue where the credential is "a curated brand's
// own sending domain", no display claim needed). The pairs are sorted by brand,
// not domain, so build a sorted domain index once on first use.
inline bool is_auth_set_domain(const std::string& org_domain) {
  if (org_domain.empty()) { return false;
}
  static const std::vector<std::uint64_t> kDomains = [] {
    std::vector<std::uint64_t> v;
    v.reserve(kKbBrandAuthPairsCount);
    for (auto const kKbBrandAuthPair : kKbBrandAuthPairs) { v.push_back(kKbBrandAuthPair.domain);
}
    std::sort(v.begin(), v.end());
    v.erase(std::unique(v.begin(), v.end()), v.end());
    return v;
  }();
  return std::binary_search(kDomains.begin(), kDomains.end(), fnv1a_lower(org_domain));
}

// The message's DMARC outcome, as a THREE-state verdict. The brand-ownership exonerations below
// must distinguish Unknown (no Authentication-Results header to judge) from Fail (an AR that did
// not pass): a forged From to the brand's own domain FAILS DMARC and is still impersonation, but
// legit brand mail that merely lacks an AR stamp must not be condemned. This type exists so the
// FP-safe rule "exonerate unless DMARC positively FAILED" cannot be re-collapsed into a boolean
// (the bug that regressed this exoneration twice: DKIM-only, then dmarc_pass, each folding Unknown
// into the condemn side). The only state that blocks exoneration is Fail.
enum class DmarcVerdict : std::uint8_t { Unknown, Pass, Fail };

// The sender is authenticated AS brand X on a domain X owns: From's org-domain is in X's
// authenticated set, DMARC did not positively fail, and the domain is NOT a shared sender platform.
// A shared webmail / publishing host (icloud.com, outlook.com, ...) cannot vouch for a brand
// identity even when it is in the brand's auth set: anyone can send from it, and a brand does not
// brand-send from its users' webmail domain (Apple does not send "Apple" mail from icloud.com), so a
// brand display from there is impersonation, not the brand (TASK-246). The caller supplies the
// shared fact (is_shared_sender_platform lives in the decision layer). The single shared gate for the
// claimed-vs-authenticated exoneration (used by the display / local-part / multi-word join paths).
inline bool authenticated_as_brand(const std::string& brand, const std::string& org_domain,
                                   DmarcVerdict verdict, bool org_is_shared_platform) {
  return !org_is_shared_platform && verdict != DmarcVerdict::Fail &&
         domain_in_brand_auth_set(brand, org_domain);
}

// The From org-domain is a curated canonical brand domain, DMARC did not positively fail, and it is
// not a shared sender platform. The fallback exoneration for the multi-word join path: a matched join
// form the KB does not key its own auth pairs for (e.g. "Free Mobile" -> freemobile, keyed under a
// primary rather than the joined alias) cannot use authenticated_as_brand, so the curated canonical
// set vouches for it -- same `verdict != Fail` and not-shared rules, one less precise membership test.
inline bool authenticated_canonical(const std::string& org_domain, DmarcVerdict verdict,
                                    bool org_is_shared_platform) {
  return !org_is_shared_platform && verdict != DmarcVerdict::Fail && is_canonical_domain(org_domain);
}

// The label is exactly a curated brand's SLD ("paypal", "boursorama").
inline bool is_brand_sld(const std::string& sld) {
  if (sld.size() < 4) { return false;
}
  const std::uint64_t h = fnv1a_lower(sld);
  return std::binary_search(kKbBrandSldHashes, kKbBrandSldHashes + kKbBrandSldHashesCount, h);
}

// The hyphen-stripped form of a multi-word brand SLD ("deutschebank" for
// deutsche-bank.de, "creditagricole" for credit-agricole.fr). A display name
// written as separate words concatenates to this; the hyphenated canonical SLD
// would never match it. Used only by the multi-word JOIN matcher below.
inline bool is_joined_sld(const std::string& joined) {
  if (joined.size() < 6) { return false;
}
  const std::uint64_t h = fnv1a_lower(joined);
  return std::binary_search(kKbJoinedSldHashes, kKbJoinedSldHashes + kKbJoinedSldHashesCount, h);
}

// Multi-word brand JOIN (TASK-214, fr/de recall). The single-token matcher misses
// a brand written as separate display words ("La Poste", "Deutsche Bank", "Bank of
// America") because no individual token is the brand. This concatenates adjacent
// tokens (windows of 2-3, so connector words like "of"/"de" fold in transparently)
// and matches the run against the CURATED brand set only: a single-label SLD
// (laposte, societegenerale, bankofamerica) or a joined hyphenated SLD
// (deutschebank). KB-anchored, not the broad Tranco set, because a multi-word legit
// org name often concatenates to a popular stem it does not send from ("World
// Wildlife Fund" -> worldwildlife, sent from wwf.org); the curated set has no such
// ambiguity, so a hit is high-confidence Tier-1. The structural owns-prefix case is exempt here
// (a domain stem the joined brand sits at the front of, "La Poste" under laposte.fr, IS the brand);
// the authenticated-domain exemption is left to the combine, which routes the returned brand
// through the same claimed-vs-authenticated gate as the single-token paths.
inline brand_names::BrandMatch display_join_impersonates(const std::string& display_name,
                                                         const std::string& from_org_domain) {
  brand_names::BrandMatch m;
  if (display_name.empty() || from_org_domain.empty()) { return m;
}
  const std::vector<brand_names::DisplayToken> tokens = brand_names::tokenize_display(display_name);
  if (tokens.empty()) { return m;
}
  // This identifies the multi-word brand a display CLAIMS and exempts only the structural
  // owns-prefix case (the sender's stem IS the brand). The authenticated-domain exemption is NOT
  // applied here: the matched brand is returned so the combine routes it through the same
  // claimed-vs-authenticated gate (authenticated_as_brand / authenticated_canonical) as bm/lp.
  const std::string fstem = brand_names::domain_stem(from_org_domain);
  // A brand's own hyphenated domain (deutsche-bank.com -> stem "deutsche-bank")
  // owns the hyphen-free join form "deutschebank", so for a hyphenated stem also
  // accept the hyphen-stripped form. Both tests are EQUALITY.
  //
  // This used to accept a PREFIX for the non-hyphenated case, and that was the
  // hole TASK-440 walked through: "geeksquad-invoice-dept.com" has the stem
  // "geeksquad-invoice-dept", which starts with "geeksquad", so the reported Geek
  // Squad scam was exempted as the brand owning its own name. A stem that merely
  // begins with a brand is the definition of a combosquat, and the hyphenated
  // branch already knew that ("deutsche-bank-secure" is a longer string, not the
  // brand); the non-hyphenated branch just did not.
  //
  // Nothing legitimate is lost by tightening it, because ownership is not this
  // function's job: a domain the brand really does send from is either in the KB's
  // canonical set or authenticates as the brand, and the combine routes every
  // match returned here through authenticated_as_brand / authenticated_canonical
  // before anything condemns. Prefix-exemption here short-circuited that check.
  std::string fstem_joined;
  if (fstem.find('-') != std::string::npos) {
    for (char const c : fstem) {
      if (c != '-') { fstem_joined.push_back(c);
}
    }
  }
  auto const owns = [&](const std::string& form) {
    return fstem == form || fstem_joined == form;
  };
  auto const is_brand_join = [](const std::string& j) {
    return is_brand_sld(j) || is_joined_sld(j);
  };
  // A SINGLE token can be a multi-word brand's join, and missing that left the
  // letter-spacing evasion half-open after TASK-459 closed it for single-word
  // brands. tokenize_display now collapses a run of single-character tokens, so
  // "D e u t s c h e B a n k" arrives here as ONE token "deutschebank": the
  // display's own word boundary is not recoverable from a string that separates
  // every letter. With the >= 2 guard this returned immediately, and
  // brand_tier has no hyphenless "deutschebank", so the claim was 0 while
  // "Deutsche Bank" was 1. Found by a cold review, which is also why the join
  // matcher is the right place for it rather than a second collapse rule:
  // is_joined_sld exists precisely to hold these hyphen-stripped forms.
  // NARROW ON PURPOSE, and the first version was not. It ran is_brand_join over
  // EVERY token, and that predicate includes is_brand_sld, so "Apple Valley
  // News" and "Amazon River" matched Tier-1 here and never reached the Tier-2
  // impersonation shape guard that exists to keep exactly those out. Four tests
  // caught it immediately, which is what those tests are for.
  //
  // Two restrictions, each carrying its own reason:
  //   spaced_join  the token came from collapsing a letter-spaced run, so its
  //                internal word boundaries are genuinely unrecoverable. An
  //                ordinary token has boundaries and belongs to the tiered paths.
  //   is_joined_sld ONLY, never is_brand_sld: a single-word brand written with
  //                spaces ("A m a z o n") is already handled by brand_tier on
  //                the normal path, with its tier and shape rules intact. What
  //                needs this is the multi-word brand whose canonical SLD is
  //                hyphenated, which is the one form no other path can see.
  for (const brand_names::DisplayToken& t : tokens) {
    if (!t.spaced_join) { continue;
}
    const std::string* form = is_joined_sld(t.plain) ? &t.plain
                            : (t.perturbed && is_joined_sld(t.conf)) ? &t.conf : nullptr;
    if (!form) { continue;
}
    if (owns(*form)) { return brand_names::BrandMatch{};
}
    m.tier1 = true;
    m.brand = *form;
    return m;
  }
  for (std::size_t i = 0; i + 1 < tokens.size(); ++i) {
    std::string plain;
    std::string conf;
    bool perturbed = false;
    for (std::size_t j = i; j < tokens.size() && j < i + 3; ++j) {
      plain += tokens[j].plain;
      conf += tokens[j].conf;
      perturbed = perturbed || tokens[j].perturbed;
      if (j == i) { continue;  // a join is >= 2 tokens
}
      const std::string* form = is_brand_join(plain) ? &plain
                              : (perturbed && is_brand_join(conf)) ? &conf : nullptr;
      if (!form) { continue;
}
      if (owns(*form)) {
        return brand_names::BrandMatch{};  // sender's stem IS the brand -> not a spoof
}
      // A non-owned multi-word brand claim: Tier-1, carrying the matched brand for the combine.
      m.tier1 = true;
      m.brand = *form;
      return m;
    }
  }
  return m;
}

// True when a and b differ by exactly one edit (insert / delete / substitute).
// Transposition is not counted (a v1 simplification); identical strings are false.
inline bool within_edit1(const std::string& a, const std::string& b) {
  const int la = static_cast<int>(a.size());
  const int lb = static_cast<int>(b.size());
  if (la - lb > 1 || lb - la > 1) { return false;
}
  int i = 0;
  int j = 0;
  int diff = 0;
  while (i < la && j < lb) {
    if (a[i] == b[j]) { ++i; ++j; continue; }
    if (++diff > 1) { return false;
}
    if (la == lb) { ++i; ++j; }   // substitution
    else if (la > lb) { ++i; }    // deletion from a
    else { ++j; }                 // insertion into a
  }
  diff += (la - i) + (lb - j);
  return diff == 1;
}

// The SENDING domain is a cousin of a DISTINCTIVE (Tier-1) brand: its SLD is that
// brand's SLD on a non-canonical domain (TLD-swap), or it is within one edit of the
// brand's SLD (typosquat). Gated to Tier-1 so common-word brand SLDs (orange, visa)
// don't flag legit regional domains. The sender's own canonical domains are exempt.
// The distinctive (Tier-1, len>=5, non-generic) KB brand SLDs, computed once.
// brand_tier over these compile-time-constant strings is invariant per email, so
// caching it turns ~N binary-searches/email into a one-time cost (the typosquat
// loop then just runs within_edit1 over the cached strings).
inline const std::vector<std::string>& distinctive_slds() {
  static const std::vector<std::string> v = [] {
    std::vector<std::string> out;
    for (const auto *kKbBrandSldString : kKbBrandSldStrings) {
      const std::string s = kKbBrandSldString;
      if (s.size() >= 5 && brand_names::is_distinctive_brand(s)) { out.push_back(s);
}
    }
    return out;
  }();
  return v;
}

// TLD-swap: the sending domain's SLD is EXACTLY a distinctive brand SLD on a
// non-canonical domain (paypal.co vs paypal.com). This is AMBIGUOUS with a legit
// regional domain the KB has not enumerated (paypal.de, netflix.de, lidl.es): both
// are the brand SLD on another valid TLD, header-identical when DMARC-aligned. So
// it is NOT a standalone condemn; the caller requires a corroborating signal
// (throwaway / free-host signer) before it counts, exactly like a Tier-2 claim.
// A legit regional brand signs aligned from its own domain, never via a throwaway,
// so corroboration-gating eliminates the regional false-positive class.
inline bool is_tld_swap_kb(const std::string& org_domain) {
  if (is_canonical_domain(org_domain)) { return false;
}
  const std::string sld = brand_names::domain_stem(org_domain);
  if (sld.size() < 4) { return false;
}
  return is_brand_sld(sld) && brand_names::is_distinctive_brand(sld);
}

// Typosquat: the sending domain's SLD is within one edit of a distinctive brand
// SLD (length-gated to >= 5, Tier-1 only). Returns the matched brand SLD ("" if
// none). NOT an unambiguous morph on its own: a brand never sends from a one-edit
// corruption of its OWN name, but OTHER legit companies sit one edit from a brand's
// name (lacoste.com vs laposte, telecom.pt vs telekom, amelie.fr vs ameli, klara.com
// vs klarna: real FPs, none Tranco-rescued). The caller therefore condemns
// standalone only when the sender also CLAIMS the returned brand (display / local
// part); an unclaimed one-edit domain is ambiguous with a legit same-name company
// and joins the corroboration-gated Tier-2 path, exactly like the TLD-swap.
inline std::string typosquat_target_kb(const std::string& org_domain) {
  if (is_canonical_domain(org_domain)) { return "";
}
  const std::string sld = brand_names::domain_stem(org_domain);
  if (sld.size() < 5) { return "";
}
  for (const std::string& b : distinctive_slds()) {
    if (within_edit1(sld, b)) { return b;
}
  }
  return "";
}

// Cross-script / IDN homoglyph of a curated KB brand (TASK-237 AC#3). is_lookalike_domain
// folds onto the Tranco single-token brand set; this adds the KB's brand + joined SLDs,
// so a Cyrillic/Greek look-alike of a multi-word brand whose hyphens drop out under
// folding (dеutsche-bank -> deutschebank, сredit-agricole -> creditagricole) is caught.
// A homoglyph is an unambiguous MORPH, never legit -> the caller treats it as Tier-1.
inline bool is_idn_lookalike_kb(const std::string& org_domain) {
  if (is_canonical_domain(org_domain)) { return false;
}
  const std::string uni =
      brand_names::confusable_fold_unicode(brand_names::domain_stem(org_domain));
  if (uni.size() < 4) { return false;
}
  return is_brand_sld(uni) || is_joined_sld(uni);
}

} // namespace spam_engine::brand_kb
