#pragma once

// Established-brand / known-ESP DKIM-signer reputation (TASK-170).
//
// The ham-side counterpart of decision_layer's free-host/throwaway SPAM offset:
// a neural-confident-wrong verdict on mail signed by an established brand or a
// clean ESP gets a soft ham-ward nudge. The set is Tranco top-N + curated ESPs,
// embedded as sorted 64-bit FNV-1a hashes (brand_reputation_data.h, generated by
// pythonDiscovery/scripts/gen_brand_reputation.py).
//
// EXACT membership by design — NOT a probabilistic filter. A bloom/cuckoo filter's
// only error is a false positive ("is a brand" when it isn't), which here would
// rescue a spam signer → a missed spam. Exact (binary search over the sorted hash
// array) is tiny (~80KB) and has no such error. See doc-11 / TASK-170.

#include <algorithm>
#include <cstdint>
#include <string>

#include "brand_reputation_data.h"
#include "decision_layer.h"
#include "fnv1a.h"

namespace spam_engine {
namespace brand_reputation {

// True when the DKIM signing org-domain is a Tranco-established brand or a
// curated clean ESP. Caller passes the eTLD+1 reduction (org_domain()).
// Membership is exact: shared fnv1a_lower (fnv1a.h) + binary search; the data is
// pinned cross-language (here, gen_brand_reputation.py, AuthFeatures.swift) by
// test_decision_layer_sync.test_brand_reputation_data_parity.
inline bool is_established_brand(const std::string& dkim_signing_org_domain) {
  if (dkim_signing_org_domain.empty()) return false;
  const std::uint64_t h = fnv1a_lower(dkim_signing_org_domain);
  return std::binary_search(kBrandHashes, kBrandHashes + kBrandHashCount, h);
}

// The brand-reputation ham offset (TASK-170): the ham-ward mirror of
// decision::sender_auth_offset. Lives here, not in decision_layer.h, because it
// needs the 10k-hash data; takes the cheap auth booleans so the conditions
// SHORT-CIRCUIT before the binary search (a free-host/throwaway/high-spam signer
// never pays for the 10k lookup). The free-host/throwaway guards are
// LOAD-BEARING, not redundant: firebaseapp.com is a free host AND a Tranco
// top-10k brand (rank ~4072), so it is in the brand set — the guard stops it
// (and other popular-but-abused signers) from being exonerated. Mirror:
// AuthFeatures.hamConfidenceOffset(rawSpamSide:).
inline double brand_reputation_offset(const std::string& dkim_signing_org_domain,
                                      double raw_spam_side, bool free_host_signed,
                                      bool signer_throwaway) {
  if (free_host_signed || signer_throwaway ||
      raw_spam_side >= decision::kBrandReputationCeiling ||
      !is_established_brand(dkim_signing_org_domain)) {
    return 0.0;
  }
  return decision::kSenderAuthEstablishedBrand;
}

}  // namespace brand_reputation
}  // namespace spam_engine
