FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    postfix \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY postfix-main.cf /etc/postfix/main.cf
COPY postfix-entrypoint.sh /entrypoint.sh

RUN postconf -e 'maillog_file=/dev/stdout' && chmod +x /entrypoint.sh

EXPOSE 25

CMD ["/entrypoint.sh"]
